name: Deploy Slides to GitHub Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Prepare deployment directory
      run: |
        mkdir -p _site
        
        # Copy the HTML file as index.html
        cp slides.html _site/index.html
        
        # Copy the slides_files directory (revealjs assets)
        if [ -d "slides_files" ]; then
          cp -r slides_files _site/
        fi
        
        # Copy custom CSS file
        if [ -f "custom.css" ]; then
          cp custom.css _site/
        fi
        
        # Copy all background images from img directory
        if [ -f "img/chatbot_black_mirror.png" ]; then
          cp img/chatbot_black_mirror.png _site/
        fi
        
        if [ -f "img/chatbot_dogs.png" ]; then
          cp img/chatbot_dogs.png _site/
        fi
        
        if [ -f "img/archie.jpg" ]; then
          cp img/archie.jpg _site/
        fi
        
        if [ -f "img/ostrich_black_box.png" ]; then
          cp img/ostrich_black_box.png _site/
        fi
        
        if [ -f "img/chatbot_invasion.png" ]; then
          cp img/chatbot_invasion.png _site/
        fi
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4